# Bradford25 Dwell Insights (Helen Request)

This notebook quickly analyses the quarterly dwell data provided for the Bradford BID area in 2024 and 2025.

In [29]:
pip install matplotlib geopandas numpy scipy folium plotly

Requirement already satisfied: matplotlib in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (3.10.7)
Requirement already satisfied: geopandas in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (1.1.2)
Requirement already satisfied: numpy in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (2.3.5)
Requirement already satisfied: scipy in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (1.16.3)
Requirement already satisfied: folium in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (0.20.0)
Requirement already satisfied: plotly in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (6.5.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from matplotlib) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pyogrio>=0.7.2 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from geopandas) (0.12.1)
Requirement already satisfied: pandas>=2.0.0 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from geopandas) (2.3.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: branca>=0.6.0 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: requests in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from folium) (2.32.5)
Requirement already satisfied: xyzservices in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from folium) (2025.11.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from plotly) (2.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: pytz>=2020.1 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from pyogrio>=0.7.2->geopandas) (2026.1.4)
Requirement already satisfied: six>=1.5 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from requests->folium) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from requests->folium) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\ProgramData\anaconda3\envs\timeseries_311\Lib\site-packages (from requests->folium) (2.6.3)
Note: you may need to restart the kernel to use updated packages.

In [30]:
#Import packages
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import geopandas as gpd
import numpy as np

In [31]:
dwell_Q1_24 = pd.read_csv(r"C:\Users\qxnq723\Desktop\Project 1\HUQ Data\FW_ Dwell Time data to analyse please\Q1_24_Bradford_Dwell.csv")
dwell_Q1_25 = pd.read_csv(r"C:\Users\qxnq723\Desktop\Project 1\HUQ Data\FW_ Dwell Time data to analyse please\Q1_25_Bradford_Dwell.csv")
dwell_Q2_24 = pd.read_csv(r"C:\Users\qxnq723\Desktop\Project 1\HUQ Data\FW_ Dwell Time data to analyse please\Q2_24_Bradford_Dwell.csv")
dwell_Q2_25 = pd.read_csv(r"C:\Users\qxnq723\Desktop\Project 1\HUQ Data\FW_ Dwell Time data to analyse please\Q2_25_Bradford_Dwell.csv")
dwell_Q3_24 = pd.read_csv(r"C:\Users\qxnq723\Desktop\Project 1\HUQ Data\FW_ Dwell Time data to analyse please\Q3_24_Bradford_Dwell.csv")
dwell_Q3_25 = pd.read_csv(r"C:\Users\qxnq723\Desktop\Project 1\HUQ Data\FW_ Dwell Time data to analyse please\Q3_25_Bradford_Dwell.csv")
dwell_Q4_24 = pd.read_csv(r"C:\Users\qxnq723\Desktop\Project 1\HUQ Data\FW_ Dwell Time data to analyse please\Q4_24_Bradford_Dwell.csv")
dwell_Q4_25 = pd.read_csv(r"C:\Users\qxnq723\Desktop\Project 1\HUQ Data\FW_ Dwell Time data to analyse please\Q4_25_Bradford_Dwell.csv")

In [32]:
#Add year and quarter columns to each dataset
dwell_Q1_24['year'] = 2024
dwell_Q1_24['quarter'] = 1

dwell_Q1_25['year'] = 2025
dwell_Q1_25['quarter'] = 1

dwell_Q2_24['year'] = 2024
dwell_Q2_24['quarter'] = 2

dwell_Q2_25['year'] = 2025
dwell_Q2_25['quarter'] = 2

dwell_Q3_24['year'] = 2024
dwell_Q3_24['quarter'] = 3

dwell_Q3_25['year'] = 2025
dwell_Q3_25['quarter'] = 3

dwell_Q4_24['year'] = 2024
dwell_Q4_24['quarter'] = 4

#That quarter has different format so standardize it
dwell_Q4_25['year'] = 2025
dwell_Q4_25['quarter'] = 4
dwell_Q4_25 = dwell_Q4_25.drop(columns= ['Value (Weekdays only)', 'Value (Weekends only)'])
dwell_Q4_25 = dwell_Q4_25.rename(columns={'Value (All days of week)': 'Value'})
dwell_Q4_25 = dwell_Q4_25.rename(columns={'area': 'Area'})
dwell_Q4_25 = dwell_Q4_25.rename(columns={'common.dataType': 'Data Type'})

In [33]:
#Concatenate the datasets together
dwell = pd.concat([dwell_Q1_24,
                   dwell_Q1_25,
                   dwell_Q2_24,
                   dwell_Q2_25,
                   dwell_Q3_24,
                   dwell_Q3_25,
                   dwell_Q4_24,
                   dwell_Q4_25
                    ], axis=0)

dwell.info()

<class 'pandas.core.frame.DataFrame'>
Index: 105 entries, 0 to 13
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Area       105 non-null    object
 1   Data Type  105 non-null    object
 2   Category   105 non-null    object
 3   Value      105 non-null    object
 4   year       105 non-null    int64
 5   quarter    105 non-null    int64
dtypes: int64(2), object(4)
memory usage: 5.7+ KB

In [34]:
dwell['Data Type'].unique()

array(['Dwell Time Distribution', 'Dwell Time by Day of Week'],
      dtype=object)

In [35]:
#Separate the 'Dwell Time Distribution' from the 'Dwell Time by Day of Week'

dwell_distribution = dwell[dwell['Data Type'] == 'Dwell Time Distribution']

dwell_week = dwell[dwell['Data Type'] == 'Dwell Time by Day of Week']

In [36]:
dwell_week.head(20)

,Area,Data Type,Category,Value,year,quarter
6,Bradford BID,Dwell Time by Day of Week,Monday,100.5 minutes,2024,1
7,Bradford BID,Dwell Time by Day of Week,Tuesday,100.6 minutes,2024,1
8,Bradford BID,Dwell Time by Day of Week,Wednesday,135.9 minutes,2024,1
9,Bradford BID,Dwell Time by Day of Week,Thursday,112.7 minutes,2024,1
10,Bradford BID,Dwell Time by Day of Week,Friday,112.4 minutes,2024,1
11,Bradford BID,Dwell Time by Day of Week,Saturday,134.3 minutes,2024,1
12,Bradford BID,Dwell Time by Day of Week,Sunday,150.1 minutes,2024,1
6,Bradford BID,Dwell Time by Day of Week,Monday,281.4 minutes,2025,1
7,Bradford BID,Dwell Time by Day of Week,Tuesday,218.3 minutes,2025,1
8,Bradford BID,Dwell Time by Day of Week,Wednesday,230.5 minutes,2025,1
9,Bradford BID,Dwell Time by Day of Week,Thursday,244.1 minutes,2025,1
10,Bradford BID,Dwell Time by Day of Week,Friday,216.2 minutes,2025,1
11,Bradford BID,Dwell Time by Day of Week,Saturday,231.8 minutes,2025,1
12,Bradford BID,Dwell Time by Day of Week,Sunday,250.7 minutes,2025,1
6,Bradford BID,Dwell Time by Day of Week,Monday,258.8 minutes,2024,2
7,Bradford BID,Dwell Time by Day of Week,Tuesday,222.8 minutes,2024,2
8,Bradford BID,Dwell Time by Day of Week,Wednesday,261.6 minutes,2024,2
9,Bradford BID,Dwell Time by Day of Week,Thursday,272.1 minutes,2024,2
10,Bradford BID,Dwell Time by Day of Week,Friday,259.8 minutes,2024,2
11,Bradford BID,Dwell Time by Day of Week,Saturday,224.5 minutes,2024,2

In [37]:
dwell_week['Area'].unique()

array(['Bradford BID', 'Bradford Bid'], dtype=object)

In [38]:
#Take out the minutes string
dwell_week['Value'] = dwell_week['Value'].str.replace(' minutes', '')
#Convert Value column to numerical instead of object
dwell_week['Value'] = pd.to_numeric(dwell_week['Value'], errors='coerce')
dwell_week.head()

C:\Users\qxnq723\AppData\Local\Temp\ipykernel_35960\137484007.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dwell_week['Value'] = dwell_week['Value'].str.replace(' minutes', '')
C:\Users\qxnq723\AppData\Local\Temp\ipykernel_35960\137484007.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dwell_week['Value'] = pd.to_numeric(dwell_week['Value'], errors='coerce')

            Area                  Data Type   Category  Value  year  quarter
6   Bradford BID  Dwell Time by Day of Week     Monday  100.5  2024        1
7   Bradford BID  Dwell Time by Day of Week    Tuesday  100.6  2024        1
8   Bradford BID  Dwell Time by Day of Week  Wednesday  135.9  2024        1
9   Bradford BID  Dwell Time by Day of Week   Thursday  112.7  2024        1
10  Bradford BID  Dwell Time by Day of Week     Friday  112.4  2024        1

In [39]:
# Get averages of days in each quarter
quarter_summary = (
    dwell_week
    .groupby(['quarter', 'year'])['Value']
    .mean()
    .unstack('year'))

#Calculate percentage chnage in quarters between 2024 and 2025
quarter_summary['pct_change_24-25'] = ((quarter_summary[2025] - quarter_summary[2024]) / quarter_summary[2024] * 100)

quarter_summary

year           2024        2025  pct_change_24-25
quarter
1        120.928571  239.000000         97.637330
2        262.171429  232.242857        -11.415650
3        123.785714  267.242857        115.891518
4        220.728571  312.400000         41.531292

In [40]:
#Get average of quarters over years
data_per_year = (dwell_week.groupby(['year'])['Value'].mean())
print(data_per_year)

year
2024    181.903571
2025    262.721429
Name: Value, dtype: float64